# This is a basic workflow to help you get started with Actions

name: Test

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install NODE JS
      uses: actions/setup-node@v2
      with:
        cache-dependency-path: test/test_solidity_project/yarn.lock
        node-version: 18
        cache: 'yarn'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          scripts/requirements.txt
          test/requirements.txt

    - name: Install building tools
      run: pip3 install -r scripts/requirements.txt

    - name: Install testing staff
      run: pip3 install -r test/requirements.txt

    - name: Install geth
      run: |
        sudo add-apt-repository -y ppa:ethereum/ethereum
        sudo apt install ethereum

    - name: Check types
      run: mypy src

    - name: Lint python
      env:
        PYTHONPATH: ./
      run: pylint src

    - name: Build pip package
      env:
        VERSION: "0.0.0"
        PYTHONPATH: ./
      run: ./scripts/build_package.sh

    - name: Compile test contract
      working-directory: test/test_solidity_project
      run: |
        yarn install

    - name: Run tests
      run: |
        pytest --cov=src.predeployed_generator
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} || echo "Codecov did not collect coverage reports"
